version: '2'
services:
  dev:
    build: .
    image: node_app
    volumes:
      - .:/home/phantom/app
      - .docker/.bash_history:/home/phantom/.bash_history
    environment:
      - SERVICE_NAME=node_app.dev
